apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abilgin-portfolio-image
  template:
    metadata:
      labels:
        app: abilgin-portfolio-image
    spec:
      hostNetwork: true                # Enabling "host network" mode for the pod
      containers:
        - name: abilgin-portfolio-image
          image: 611289949201.dkr.ecr.us-east-1.amazonaws.com/abilgin-portfolio-image:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: abilgin-nodeport
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 31004   # Specify the nodePort you want to use (in the range 30000-32767)
  selector:
    app: abilgin-portfolio-image

