apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abilgin-portfolio-image
  template:
    metadata:
      labels:
        app: abilgin-portfolio-image
    spec:
      containers:
        - name: abilgin-portfolio-image
          image: 611289949201.dkr.ecr.us-east-1.amazonaws.com/abilgin-portfolio-image:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: abilgin-alb
spec:
  type: LoadBalancer
  selector:
    app: abilgin-portfolio-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
