apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: your-container-name
          image: 611289949201.dkr.ecr.us-east-1.amazonaws.com/abilgin-portfolio-image:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: your-service-name
spec:
  type: LoadBalancer
  selector:
    app: your-app-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
